/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Tqv9173Hh7h
 */
import React from "react";
import Link from "next/link";

export function AlbumList({
  albums,
}: {
  albums: {
    id: React.Key;
    title: React.ReactNode;
    user: {
      name?: React.ReactNode;
    };
    photos: { url: string }[];
  }[];
}) {
  return (
    <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-4 md:p-6">
      {albums.map((album) => (
        <div
          key={album.id}
          className="relative group overflow-hidden rounded-lg"
        >
          <Link
            className="absolute inset-0 z-10 flex items-center justify-center"
            href={`/albums/${album.id}`}
          >
            <svg
              className=" h-10 w-10 text-white opacity-0 group-hover:opacity-100"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
            <span className="sr-only">Play Album</span>
          </Link>
          <img
            alt="Album 1"
            className="object-cover w-full h-60 transition-transform duration-300 ease-in-out group-hover:scale-110"
            height={400}
            src={album.photos[0]?.url}
            style={{
              aspectRatio: "400/400",
              objectFit: "cover",
            }}
            width={400}
          />
          <div className="bg-white p-4 dark:bg-zinc-950">
            <h3 className="font-semibold text-lg md:text-xl">{album.title}</h3>
            <p className="text-sm text-zinc-500 dark:text-zinc-400">
              {album.user.name}
            </p>
          </div>
        </div>
      ))}
    </section>
  );
}
