/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hhec5skVj0u
 */
import Link from "next/link";

export function AlbumListSkeleton() {
  return (
    <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-4 md:p-6 dark:bg-gray-800">
      <div className="animate-pulse relative group overflow-hidden rounded-lg">
        <Link
          className="absolute inset-0 z-10 flex items-center justify-center"
          href="#"
        >
          <svg
            className=" h-10 w-10 text-white dark:text-gray-800 opacity-0 group-hover:opacity-100"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <polygon points="5 3 19 12 5 21 5 3" />
          </svg>
          <span className="sr-only">Loading Album</span>
        </Link>
        <div className="bg-gray-300 dark:bg-gray-700 h-60 w-full" />
        <div className="bg-white dark:bg-gray-800 p-4">
          <div className="h-5 bg-gray-300 dark:bg-gray-700 mb-2" />
          <div className="h-3 bg-gray-300 dark:bg-gray-700" />
        </div>
      </div>
      <div className="animate-pulse relative group overflow-hidden rounded-lg">
        <Link
          className="absolute inset-0 z-10 flex items-center justify-center"
          href="#"
        >
          <svg
            className=" h-10 w-10 text-white dark:text-gray-800 opacity-0 group-hover:opacity-100"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <polygon points="5 3 19 12 5 21 5 3" />
          </svg>
          <span className="sr-only">Loading Album</span>
        </Link>
        <div className="bg-gray-300 dark:bg-gray-700 h-60 w-full" />
        <div className="bg-white dark:bg-gray-800 p-4">
          <div className="h-5 bg-gray-300 dark:bg-gray-700 mb-2" />
          <div className="h-3 bg-gray-300 dark:bg-gray-700" />
        </div>
      </div>
      <div className="animate-pulse relative group overflow-hidden rounded-lg">
        <Link
          className="absolute inset-0 z-10 flex items-center justify-center"
          href="#"
        >
          <svg
            className=" h-10 w-10 text-white dark:text-gray-800 opacity-0 group-hover:opacity-100"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <polygon points="5 3 19 12 5 21 5 3" />
          </svg>
          <span className="sr-only">Loading Album</span>
        </Link>
        <div className="bg-gray-300 dark:bg-gray-700 h-60 w-full" />
        <div className="bg-white dark:bg-gray-800 p-4">
          <div className="h-5 bg-gray-300 dark:bg-gray-700 mb-2" />
          <div className="h-3 bg-gray-300 dark:bg-gray-700" />
        </div>
      </div>
      <div className="animate-pulse relative group overflow-hidden rounded-lg">
        <Link
          className="absolute inset-0 z-10 flex items-center justify-center"
          href="#"
        >
          <svg
            className=" h-10 w-10 text-white dark:text-gray-800 opacity-0 group-hover:opacity-100"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <polygon points="5 3 19 12 5 21 5 3" />
          </svg>
          <span className="sr-only">Loading Album</span>
        </Link>
        <div className="bg-gray-300 dark:bg-gray-700 h-60 w-full" />
        <div className="bg-white dark:bg-gray-800 p-4">
          <div className="h-5 bg-gray-300 dark:bg-gray-700 mb-2" />
          <div className="h-3 bg-gray-300 dark:bg-gray-700" />
        </div>
      </div>
    </section>
  );
}
