"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HjEYKVqSW48
 */
import { Button } from "@/components/ui/button";
import {
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenu,
  DropdownMenuItem,
  DropdownMenuShortcut,
  DropdownMenuGroup,
  DropdownMenuLabel,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { LoginDialog } from "./login-dialog";
import { gql } from "@/app/__generated__";
import { useQuery } from "@apollo/client";
import { LogOut } from "lucide-react";

const GET_VIEWER = gql(/* GraphQL */ `
  query GetViewer {
    viewer {
      name
      email
    }
  }
`);

export function PageLayout({ children }: React.PropsWithChildren<{}>) {
  const { data, refetch } = useQuery(GET_VIEWER);
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
      <header className="bg-white dark:bg-gray-800 shadow-sm w-full h-16 flex items-center justify-between px-4 md:px-6">
        <h1 className="text-xl font-semibold">Kitchensink</h1>
        <div className="flex space-x-4">
          {data?.viewer ? (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline">
                  {data?.viewer.name} ({data?.viewer.email})
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="bg-white dark:bg-gray-800 w-56">
                <DropdownMenuLabel>My Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuGroup>
                  <DropdownMenuItem
                    onClick={() => {
                      localStorage.removeItem("token");
                      refetch();
                    }}
                  >
                    <LogOut className="mr-2 h-4 w-4" />
                    <span>Log out</span>
                    <DropdownMenuShortcut>⇧⌘Q</DropdownMenuShortcut>
                  </DropdownMenuItem>
                </DropdownMenuGroup>
              </DropdownMenuContent>
            </DropdownMenu>
          ) : (
            <LoginDialog onLoginSuccess={() => refetch()} />
          )}
        </div>
      </header>
      <main className="p-4 md:p-6">{children}</main>
    </div>
  );
}
