/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ArOrJUIlBMc
 */

export function UserGridSkeleton() {
  return (
    <div className="grid grid-cols-3 gap-4">
      <div className="animate-pulse bg-blue-100 dark:bg-blue-800 p-6 rounded-lg shadow-lg">
        <div className="h-6 bg-blue-200 dark:bg-blue-700 rounded w-3/4" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-1/2" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-full" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-full" />
      </div>
      <div className="animate-pulse bg-blue-100 dark:bg-blue-800 p-6 rounded-lg shadow-lg">
        <div className="h-6 bg-blue-200 dark:bg-blue-700 rounded w-3/4" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-1/2" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-full" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-full" />
      </div>
      <div className="animate-pulse bg-blue-100 dark:bg-blue-800 p-6 rounded-lg shadow-lg">
        <div className="h-6 bg-blue-200 dark:bg-blue-700 rounded w-3/4" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-1/2" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-full" />
        <div className="h-4 mt-2 bg-blue-200 dark:bg-blue-700 rounded w-full" />
      </div>
    </div>
  );
}
