import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ApolloProvider, client } from "./apollo-client";
import "./globals.css";
import { PageLayout } from "@/components/page-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider client={client}>
          <PageLayout>{children}</PageLayout>
        </ApolloProvider>
      </body>
    </html>
  );
}
